# Generated by Django 2.2.6 on 2019-10-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwpractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
